---
title: "Quarto Slides Template - replace with lesson title"
author: "Author Name"
institute: "Research Faciliation, Dartmouth Libraries"
date: "Jan 2026"
format: 
  revealjs:
    theme: night
    navigation-mode: vertical
  
editor: visual
---

# Template Instructions

\[intro / overview\]

## Notes for Creators

1.  Review the [Quarto guide to create slide presentations](https://quarto.org/docs/presentations/)
2.  The content of the slideshow is written in markdown.
3.  you can adjust the format and metadata for the slideshow by adjusting the YAML block above.
4.  When the slideshow is complete you can convert it to a revealjs html website by selecting **Render** above. When you click the **Render** button a document will be generated that includes:
    -   Content authored with markdown
    -   Output from executable code 
    -   *Tip: run your slideshow early and often to ensure all major changes are rendered correctly.*

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

# Top-Level Slide

Create by placing `#` before the slide title

## Level 2 Slide

Create by placing `##` before the slide title
