---
title: "datasets_details"
output: html_document
---

## dataset "..movies_data.csv"
  + input = multiple csvs in data/raw
  + nb = "00_data_merge_clean.r"
  + removes rankings from titles, i.e. "1. Star Wars" becomes "Star Wars"
  + converts time durations into minutes, i.e. "2h 22m" to "142" 
  + renames some columns
  + splits `budget` and `gross_worldwide` columns into 3 separate columns for each: value, currency, and presence of word "(estimated)"
  + splits `release_date` column into year, month, day, and daynum columns

## dataset "..movies_data_subset.csv"
  + input = "movies_data.csv"
  + nb = "00_data_merge_clean.r"
  + removes some columns, reorders others

  
## dateset "..movies_data_dollars.csv"
  + input = "movies_data_subset.csv"
  + nb = "00_data_merge_clean.r"
  + filters dataset so only those where columns `budget_currency` and `grossww_currency` == "$" remain; reduces 2010-2025 dff from 9600 obs's to 2969.

## dateset "..movies_data_dollars2.csv"
  + input = "movies_data_dollars.csv"
  + nb = "02_wrangle-and-analyze..."
  + adds columns to analyze financial data, i.e.:
    + converts budget and gross columns into millions of dollars
    + calculates `net_profit_mm` (gross worldwide revenue - budget in millions)
    + calculates `net_profit_pct` (net_profit_mm / budget * 100)